workflows:
  ios-release:
    name: Build iOS Release
    environment:
      vars:
        XCODE_WORKSPACE: "PureVidAppCLI.xcworkspace"
        XCODE_SCHEME: "PureVidAppCLI"
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
          cd ios
          pod install
      - name: Build iOS app
        script: |
          xcodebuild -workspace "$XCODE_WORKSPACE" -scheme "$XCODE_SCHEME" -configuration Release -sdk iphoneos -archivePath $HOME/build/PureVid.xcarchive archive
          xcodebuild -exportArchive -archivePath $HOME/build/PureVid.xcarchive -exportOptionsPlist ios/exportOptions.plist -exportPath $HOME/build
    artifacts:
      - build/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM.zip
