platform :ios, '16.0'
use_modular_headers!

require_relative '../node_modules/react-native/scripts/react_native_pods'

target 'PureVidAppCLI' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true
  )

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        config.build_settings['SWIFT_VERSION'] = '5.0'
        # DO NOT delete deployment target!
        # config.build_settings.delete('IPHONEOS_DEPLOYMENT_TARGET') ← ❌ REMOVE THIS
      end
    end
  end
end
